"""add users table

Revision ID: 92d664f0962c
Revises: c67e109c84a7
Create Date: 2026-02-14 16:33:26.109106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92d664f0962c'
down_revision = 'c67e109c84a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('reach_cm', sa.Float(), nullable=True),
    sa.Column('avatar_style', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # Add user_id as nullable first, then backfill, then make non-nullable
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))

    # Create a default user and assign orphan projects to it
    from sqlalchemy.sql import table, column
    import sqlalchemy as _sa
    from werkzeug.security import generate_password_hash

    users_t = table('users',
        column('id', _sa.Integer),
        column('username', _sa.String),
        column('password_hash', _sa.String),
        column('avatar_style', _sa.String),
    )
    projects_t = table('projects', column('user_id', _sa.Integer))

    conn = op.get_bind()
    # Only create default user if there are orphan projects
    count = conn.execute(_sa.text("SELECT COUNT(*) FROM projects WHERE user_id IS NULL")).scalar()
    if count > 0:
        conn.execute(users_t.insert().values(
            username='admin',
            password_hash=generate_password_hash('changeme'),
            avatar_style='adventurer',
        ))
        admin_id = conn.execute(_sa.text("SELECT id FROM users WHERE username='admin'")).scalar()
        conn.execute(projects_t.update().where(projects_t.c.user_id.is_(None)).values(user_id=admin_id))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('user_id', nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    # ### end Alembic commands ###
